### ISSUE TITLE
"Download Data CSVs" does not work unless a user has "all countries" permission

### ISSUE THREAD

**Issue by toph-allen** [ecohealthalliance/wab-net-website#1]
If a user does not have "all countries" permission, clicking the "Download Data CSVs" link under the "Settings" menu will result in an error. I've written up my hunches about what might be causing this, but I'm honestly not sure.

This is caused by something going wrong in [this block of code](https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L174-L184):

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L174-L184

This is apparently using Django methods documented in these sections: [Retrieving specific objects with filters](https://docs.djangoproject.com/en/3.0/topics/db/queries/#retrieving-specific-objects-with-filters) and [Field lookups](https://docs.djangoproject.com/en/3.0/topics/db/queries/#field-lookups).

Django's field lookup argument is formulated `field__lookuptype=value`. The multiplication operator repeats a string that number of times, as in:

```python
In [4]: "foo_" * 5
Out[4]: 'foo_foo_foo_foo_foo_'
```

So this block of code is trying to look up the number of ancestors needed to get to the root object, which should contain the country property, and construct a query to go up that many levels in the database object, such as `parent__parent__country__in: user_viewable_countries`.

Nathan suggested in an email that perhaps the country names have changed such that they aren't matching. He said, "The county permissions can be debugged by print statements showing the country values in the surveys and for the user." From just checking the names of the countries and Groups on the site itself, however, it looks as though they match. And it looks as though the country names in the database match the names used in the permissions settings. And it doesn't look as though the code to construct the country name is broken.

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L157-L158

So I'm not sure what the fix is.

**Comment by RobJY** [comment]
I was able to recreate the bug with the steps listed above.  I'll look into a fix.

Great issue description!  Thank you Toph!!

**Comment by RobJY** [comment]
Changed from filtering with model data as used above to filtering the objects themselves based on new get_country() method.
