### ISSUE TITLE
"Download Occurrence Data" is broken due to use of fixed references to questions

### ISSUE THREAD

**Issue by toph-allen** [ecohealthalliance/wab-net-website#2]
The "Download Occurrence Data" function under the "Settings" menu does not work. This is because of a form update, which changed the name of some of the questions this function relies on.

The function should be updated with new references now, and should be checked every time the form is updated. Alternatively, if it's possible, it should be rethought to avoid the use of these fixed references. But I don't think that's possible. It might be easier to keep these variables in a separate place together, i.e. have a list of variables upon which site functionality depends, so they can all be updated together.

These are all such references in the `download_occurrence_data()` function:

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L226

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L227

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L229

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L236

There are a two other references in [views.py](https://github.com/ecohealthalliance/wab-net-website/blob/master/wabnet/views.py) in other functions that should also be updated, though I'm not sure what they're breaking. It might also be that they aren't broken, if they were an early question in the form (e.g. the first one below, the splash screen).

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L65

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/views.py#L273

**Comment by RobJY** [comment]
removed hard-coded labels above with function that finds correct label by using the base string.
