### ISSUE TITLE
Bug: Media files (e.g. photos) cannot be viewed by users, despite existing on the server

### ISSUE THREAD

**Issue by toph-allen** [ecohealthalliance/wab-net-website#3]
Users see errors when they click on links to view photos on the site. These photos existing the server, however, and as far as I can tell, the `settings.py` file, which defines the locations of these things for Django, is configured correctly (and didn't change before this problem started).

https://github.com/ecohealthalliance/wab-net-website/blob/5e69676bb159538db58e899b9b39d09cd2ef9067/wabnet/settings.py#L133

Nathan suggested that this might be a problem with the site's Apache server.

**Comment by RobJY** [comment]
Haven't been able to recreate this issue, yet.  Maybe it was because of the needed migration.  If columns were out of order links to images would break.

I'll keep looking into it.

**Comment by RobJY** [comment]
fixed since previous updates.
